import 'reflect-metadata';
export * from './src/register';
export * from './src/decorators';
export * from './src/cosmotype-exports';
export * from './src/base-plugin';
export * from './src/multi-plugin';
export * from './src/map-plugin';
export * from './src/plugin-factory';
export * from './src/def/interfaces';
export * from 'schemastery-gen';
